#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#                 Plugin by FlailoftheLord.                        #
#        -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                   #
#   for questions please pm me on discord at FlailoftheLord#6842   #
#          Join my discord server for faster support:              #
#                https://discord.gg/wuxW5PS                        #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------

# If set to true, you will be able to open an inventory to take your items out.
# if set to false, it will just drop your items and xp when you click the death block.
EnableInventoryMode: true
# Title shown on top of the DeathInventory if enabled.
DeathInventoryTitle: "&4&lDeath Inventory"
# message sent if somebody uses the /deathinv command, but InventoryMode is disabled.
InventoryDisabled: "%prefix% &cThe Death Inventory has been disabled, enable it in the config.yml file to use the /deathinv command"


# If EnableInventoryMode is set to false all these will be ignored.
# Message to send to the player if they close their death inventory and there  are still items inside.
InvNotEmpty: "%prefix% &cyou still have items inside your DeathInventory... take them out ASAP!"
# Message sent if the player tries to open their Empty death inventory via command.
InvEmpty: "%prefix% &cyou don't have any items in your DeathInventory!"


# MESSAGES #
# Customize the messages that the plugin sends to players

# Plugin prefix, this is set before very plugin message,
# Simply use the placeholder %prefix% in the message \(^-^)/
Prefix: "&8[&5&lD&d&lI&8]"

ReloadMessage: "%prefix% &aAll &afiles reloaded!"

NoPermissionMessage: "%prefix% &cyou don't have permission to use this."

# Message sent to player when he dies.
# use the %death-location% placeholder for the place where they died at and %world% for the world they died in.
DeathMessage: "%prefix% &7You died, and your items are stored in a block at &f%death-location% &7in world: &f%world%"

DeathLocationTeleport: "%prefix% &ayou were teleported to your death location! click the gold block to retreive your items."

ItemsRetrieved: "%prefix% &aYou got all your items back!"

CannotBreak: "%prefix% &cYou cannot break the DeathInventory block!"

# Let the players keep all their Exp on death?
KeepExp: true

# Must be the Bukkit Item Name, you can see the entire list here:
#  https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
DeathBlockType: "GOLD_BLOCK"


